world_size: -1
sharding_strategy: "torch.distributed.fsdp.api.ShardingStrategy.FULL_SHARD"
no_sync: False
master_addr: "localhost"
master_port: "12355"
save_model: False
output_dir: "output"
num_epochs: 1
profile_memory: False
loading_workers: -1
log_to: "tqdm"
seed: 42
project_name: "fsdp_qlora"
name: null
group: null
entity: null
verbose: False
max_steps: -1